### ISSUE TITLE
Smart on fhir app launch request error

### ISSUE THREAD

**Issue by guijealth** [adamyala/ecw_demo_auth#1]
Take a look at the documentation
https://build.fhir.org/ig/HL7/smart-app-launch/app-launch.html#request-4

as you can see the request param name is `scope` instead of `scopes`
<img width="645" alt="image" src="https://github.com/user-attachments/assets/38a5b4af-8534-48af-82e2-7a6f998493c8" />

[            "scopes": "launch user/Patient.read user/Encounter.read",](https://github.com/adamyala/ecw_demo_auth/blob/master/core/views.py#L42)

**Comment by guijealth** [comment]
another thing I am afraid of is the format of your scopes, the standard permissions are `c` `r` `u` `d` `s`
https://build.fhir.org/ig/HL7/smart-app-launch/scopes-and-launch-context.html#fhir-resource-scope-syntax

**Comment by adamyala** [comment]
@guillerglez88 Thank you so much for this issue. Changing `scopes` to `scope` ended up being the solution.

For some reason, the ECW does not follow the `r` scope syntax, they ask for `read`.

How did you find this repo? Is there a way I can tip you or give you a bounty for the help?

**Comment by guijealth** [comment]
You're welcome! I just saw the opportunity to help since I am familiarized with fhir. The `read` permission name for scopes is legacy, they seem to implement an older version of the standard.
